services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: node app
    restart: always